add `py.typed` file to Python module (#2323)
We provide typing stubs for the Python module so we also need to add an empty `py.typed` file so that type checking tools know to use them.

For example, assuming the following `a.py`:
```py
import f3d
engine = f3d.Engine.create()
engine.window.size = 900, 720.0
```
and running `mypy a.py` we get:
```
a.py:1: error: Skipping analyzing "f3d": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```
after adding the `py.typed` file and re-runing the same command we get the much more useful and expected:
```
a.py:3: error: Incompatible types in assignment (expression has type "tuple[int, float]", variable has type "tuple[int, int]")  [assignment]
```